[workspace]
members = ["crates/vthread", "crates/vthreads", "crates/vthread-stack", "crates/vthread-sync-core", "crates/vthread-lab"]
resolver = "3"

[workspace.package]
version = "0.0.2-rc.1"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
repository = "https://github.com/zsumz/vthread"
authors = ["vthread contributors"]

[workspace.dependencies]
vthread = { path = "crates/vthread", version = "=0.0.2-rc.1" }
vthread-stack = { path = "crates/vthread-stack", version = "=0.0.2-rc.1" }
vthread-sync-core = { path = "crates/vthread-sync-core", version = "=0.0.2-rc.1" }
zio = { version = "=0.0.1-dev.1", default-features = false }
socket2 = { version = "=0.6.5", default-features = false }
libc = "=0.2.189"
crossbeam-queue = "=0.3.13"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unreachable_pub = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"

[profile.release]
panic = "unwind"
