[workspace]
members = ["crates/vthread", "crates/vthread-stack"]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
repository = "https://github.com/zsumz/vthread"
authors = ["vthread contributors"]

[workspace.dependencies]
corosensei = { version = "=0.3.4", default-features = true }
vthread-stack = { path = "crates/vthread-stack", version = "0.0.1" }
zio = { git = "https://github.com/zsumz/zio.git", rev = "eaf713a58b9ab54b219755f5b96efa087b27ff60", default-features = false }
socket2 = { version = "=0.6.5", default-features = false }
libc = "=0.2.189"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unreachable_pub = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"

[profile.release]
panic = "unwind"
