[package]
name = "vthread-stack"
description = "Stack and context backend for vthread"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "README.md"
publish = ["crates-io"]

[features]
default = []
runtime-evidence = []

[dependencies]
corosensei.workspace = true

[lints]
workspace = true
