[package]
name = "vthread-benchmarks"
version = "0.0.0"
edition = "2024"
publish = false

[features]
allocation-probe = []
lifecycle-profiling = ["vthread/lifecycle-profiling"]

[dependencies]
httparse = "=1.10.1"
httpdate = "=1.0.3"
may = "=0.3.51"
vthread = { path = "../crates/vthread" }

[profile.release]
codegen-units = 1
lto = "thin"

[workspace]
